# Server Configuration
server:
  port: ${AUTH_SERVICE_PORT:8081}

# Spring Application Configuration
spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # default = dev if not specified

  # Common JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${SERVICE_REGISTRY:8761}/eureka/
  instance:
    prefer-ip-address: true

# Management Configuration for Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  # Actuator 
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs/v1
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /api-docs/v1/swagger-config
    url: /api-docs/v1
    display-request-duration: true