spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/hostelgrid_notification_db
    username: root
    password: Y21CSE031
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      # Configure JSON deserializer
      properties:
        "[spring.json.trusted.packages]": "com.hostelgrid.common.events"
        "[spring.json.use.type.headers]": false
        "[spring.json.value.default.type]": "com.hostelgrid.common.events.UserRegistrationEvent"
        
    # Kafka Producer Configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ayyappad2003@gmail.com
    password: lxne toiv qyob skqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: 8082

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Management Configuration for Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always