# QA Profile Configuration
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${IP:localhost}:${DB_PORT:3307}/${NOTIFICATION_SERVICE_DB_NAME:hostelgrid_notification_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${NOTIFICATION_SERVICE_PORT:8084}
  
logging:
  level:
    root: INFO
    com.hostelgrid: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics