# Eureka Service Registry Configuration
server:
  port: ${SERVICE_REGISTRY:8761}

# Spring Application Configuration 
spring:
  application:
    name: service-registry

#  profiles: 
eureka:
  instance:
    hostname: localhost

  # Eureka client configuration
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  # Security Configuration for Eureka
  # To secure Eureka, configure Spring Security in your application instead of using 'eureka.security' properties.
  security:
    username: ${EUREKA_USERNAME:admin}
    password: ${EUREKA_PASSWORD:Admin@123}


# Management Configuration for Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always


  