server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        # Authentication Service (Public)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        # Hostel Service (Protected)
        - id: hostel-service
          uri: lb://hostel-service
          predicates:
            - Path=/api/v1/hostels/**, /api/v1/branches/**, /api/v1/categories/**
          filters:
            - StripPrefix=0

        # Service Registry
        - id: service-registry
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always