# Server Configuration
server:
  port: ${STUDENT_SERVICE_PORT:8085}


# Spring Configuration
spring:
  application:
    name: student-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # JPA Configuration
  jpa:            
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # GraphQL Configuration
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql

# External Services Configuration
external:
  services:
    hostel-service:
      graphql-url: http://localhost:8083/graphql


# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${SERVICE_REGISTRY:8761}/eureka/
  instance:
    prefer-ip-address: true


# Management Configuration for Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs/v1
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /api-docs/v1/swagger-config
    url: /api-docs/v1
    display-request-duration: true