# Server Configuration
server:
  port: ${BILLING_SERVICE_PORT:8082}

# Spring Application Configuration
spring:
  application:
    name: billing-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Common JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${SERVICE_REGISTRY:8761}/eureka/
  instance:
    prefer-ip-address: true

# Management Configuration for Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs/v1
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /api-docs/v1/swagger-config
    url: /api-docs/v1
    display-request-duration: true