# Development Profile Configuration
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${BILLING_SERVICE_DB_NAME:hostelgrid_billing_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${BILLING_SERVICE_PORT:8082}

logging:
  level:
    root: INFO
    com.hostelgrid: DEBUG
    com.netflix.discovery: WARN
    com.zaxxer.hikari: WARN
    org.apache.http: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env