# Server Configuration
server:
  port: ${BILLING_SERVICE_PORT:8082}

# Spring Application Configuration
spring:
  application:
    name: billing-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://${IP:localhost}:${DB_PORT:3306}/${BILLING_SERVICE_DB_NAME:hostelgrid_billing_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Y21CSE031}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${SERVICE_REGISTRY:8761}/eureka/
  instance:
    prefer-ip-address: true


# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs/v1
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /api-docs/v1/swagger-config
    url: /api-docs/v1
    display-request-duration: true
    
# Management Configuration for Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics