# Development Profile Configuration
spring:
  datasource:
    url: jdbc:mysql://${IP:localhost}:${DB_PORT:3306}/${HOSTEL_SERVICE_DB_NAME:hostelgrid_hostel_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Y21CSE031}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${HOSTEL_SERVICE_PORT:8083}

logging:
  level:
    root: INFO
    com.hostelgrid: DEBUG
    org.springframework.graphql: DEBUG
    com.netflix.discovery: WARN
    com.zaxxer.hikari: WARN
    org.apache.http: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env