# Server Configuration
server:
  port: ${HOSTEL_SERVICE_PORT:8083}

# Spring Application Configuration
spring:
  application:
    name: hostel-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # default = dev if not specified

  # Common JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Common GraphQL Config
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
      headers:    # Add any required headers for GraphiQL requests
        Authorization: "Bearer your-jwt-token-here"
    path: /graphql
    cors:          # CORS settings for GraphQL endpoint
      allowed-origins: "http://localhost:3000,https://your-frontend.com"
      allowed-methods: GET,POST
      allowed-headers: "Authorization,Content-Type"

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${SERVICE_REGISTRY:8761}/eureka/
  instance:
    prefer-ip-address: true

# Management Configuration for Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs/v1
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /api-docs/v1/swagger-config
    url: /api-docs/v1
    display-request-duration: true
